# Generated by Django 3.2.25 on 2025-03-01 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_auto_20250301_1944'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0002_materialcontrol_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.TextField(verbose_name='Descripción del trabajo')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Horas trabajadas')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING', 'Pendiente de firma'), ('SIGNED', 'Firmado'), ('COMPLETED', 'Completado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Firma del cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to='customers.customer', verbose_name='Cliente')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Parte de trabajo',
                'verbose_name_plural': 'Partes de trabajo',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material', verbose_name='Material')),
                ('work_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_used', to='reports.workreport', verbose_name='Parte de trabajo')),
            ],
            options={
                'verbose_name': 'Material usado',
                'verbose_name_plural': 'Materiales usados',
            },
        ),
    ]
