# Generated by Django 3.2.25 on 2025-03-02 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_auto_20250302_0053'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report_images/%Y/%m/%d/', verbose_name='Imagen')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen del parte',
                'verbose_name_plural': 'Imágenes del parte',
            },
        ),
        migrations.RenameField(
            model_name='materialused',
            old_name='work_report',
            new_name='report',
        ),
        migrations.RemoveField(
            model_name='workreport',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='workreport',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='workreport',
            name='technician',
        ),
        migrations.AddField(
            model_name='workreport',
            name='incident',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to='incidents.incident', verbose_name='Incidencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('COMPLETED', 'Completado')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='after_images',
            field=models.ManyToManyField(blank=True, related_name='reports_after', to='reports.ReportImage', verbose_name='Imágenes después'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='before_images',
            field=models.ManyToManyField(blank=True, related_name='reports_before', to='reports.ReportImage', verbose_name='Imágenes antes'),
        ),
        migrations.CreateModel(
            name='TechnicianAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Horas trabajadas')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='reports.workreport', verbose_name='Parte de trabajo')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Asignación de técnico',
                'verbose_name_plural': 'Asignaciones de técnicos',
                'unique_together': {('report', 'technician')},
            },
        ),
    ]
