# Generated by Django 3.2.25 on 2025-03-02 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20250302_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workreport',
            name='title',
        ),
    ]
