# Generated by Django 3.2.25 on 2025-03-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_workreport_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreport',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas trabajadas'),
        ),
    ]
