# Generated by Django 3.2.25 on 2025-03-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_technicianassignment_hours_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianassignment',
            name='hours_worked',
        ),
    ]
