# Generated by Django 3.2.25 on 2025-03-02 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_technicianassignment_hours_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workreport',
            name='after_images',
        ),
        migrations.RemoveField(
            model_name='workreport',
            name='before_images',
        ),
        migrations.AddField(
            model_name='reportimage',
            name='image_type',
            field=models.CharField(choices=[('BEFORE', 'Antes'), ('AFTER', 'Después')], default=1, max_length=6, verbose_name='Tipo de imagen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportimage',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.workreport', verbose_name='Parte de trabajo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='image',
            field=models.ImageField(upload_to='report_images/', verbose_name='Imagen'),
        ),
    ]
