# Generated by Django 3.2.25 on 2025-03-04 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20250302_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportimage',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='image',
            field=models.ImageField(upload_to='report_images/'),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='image_type',
            field=models.CharField(choices=[('BEFORE', 'Antes'), ('AFTER', 'Después')], default='BEFORE', max_length=10),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.workreport'),
        ),
    ]
