# Generated by Django 3.2.25 on 2025-03-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20250304_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('COMPLETED', 'Completado'), ('DELETED', 'Eliminado')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
    ]
