# Generated by Django 5.1.7 on 2025-03-12 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20250306_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.workreport', verbose_name='Parte de trabajo'),
            preserve_default=False,
        ),
    ]
