# Generated by Django 5.1.7 on 2025-03-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_reportimage_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
    ]
