# Generated by Django 5.1.7 on 2025-03-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20250301_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre comercial'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CIF/NIF'),
        ),
    ]
