# Generated by Django 3.2.25 on 2025-03-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cod_worker',
            field=models.CharField(editable=False, max_length=3, unique=True),
        ),
    ]
