# Generated by Django 3.2.25 on 2025-02-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcontrol',
            name='operation',
            field=models.CharField(choices=[('ADD', 'Añadir'), ('REMOVE', 'Quitar')], default='ADD', max_length=6, verbose_name='Operación'),
        ),
    ]
