# Generated by Django 3.2.25 on 2025-03-06 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20250304_1750'),
        ('materials', '0002_materialcontrol_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcontrol',
            name='reason',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('RETIRADA', 'Retirada'), ('USO', 'Uso en reporte'), ('DEVOLUCION', 'Devolución')], default='COMPRA', max_length=10, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='materialcontrol',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_controls', to='reports.workreport', verbose_name='Reporte asociado'),
        ),
    ]
