# Generated by Django 3.2.25 on 2025-03-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20250306_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcontrol',
            name='invoice_image',
            field=models.ImageField(blank=True, null=True, upload_to='material_invoices/', verbose_name='Imagen de albarán'),
        ),
        migrations.AlterField(
            model_name='materialcontrol',
            name='reason',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('RETIRADA', 'Retirada'), ('USO', 'Uso en reporte'), ('DEVOLUCION', 'Devolución')], default='COMPRA', max_length=20, verbose_name='Motivo'),
        ),
    ]
