# Generated by Django 5.1.7 on 2025-03-08 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20250306_1334'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcontrol',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_controls', to='tickets.ticket', verbose_name='Ticket asociado'),
        ),
    ]
