# Generated by Django 5.1.7 on 2025-03-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_add_ticket_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcontrol',
            name='location_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia de ubicación'),
        ),
    ]
