# Generated by Django 5.1.7 on 2025-03-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_materialcontrol_location_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcontrol',
            name='operation',
            field=models.CharField(choices=[('ADD', 'Entrada'), ('REMOVE', 'Salida'), ('TRANSFER', 'Traslado')], default='ADD', max_length=10, verbose_name='Operación'),
        ),
        migrations.AlterField(
            model_name='materialcontrol',
            name='reason',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('DEVOLUCION', 'Devolución'), ('RETIRADA', 'Retirada'), ('VENTA', 'Venta'), ('USO', 'Uso'), ('TRASLADO', 'Traslado')], default='COMPRA', max_length=20, verbose_name='Motivo'),
        ),
    ]
