# Generated by Django 5.1.7 on 2025-03-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_alter_materialcontrol_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcontrol',
            name='movement_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del movimiento asociado'),
        ),
    ]
