# Generated by Django 5.1.7 on 2025-03-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_materialcontrol_movement_id'),  # Asegúrate de que esta sea la migración anterior correcta
    ]

    # Sin operaciones, solo para marcar esta migración como aplicada
    operations = []
