# Generated by Django 5.1.7 on 2025-03-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_fix_movement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcontrol',
            name='reason',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('RETIRADA', 'Retirada'), ('USO', 'Uso en reporte'), ('DEVOLUCION', 'Devolución'), ('TRASLADO', 'Traslado'), ('CUADRE', 'Cuadre de inventario')], default='COMPRA', max_length=20, verbose_name='Motivo'),
        ),
    ]
