# Generated by Django 5.1.7 on 2025-03-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_alter_materialcontrol_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialcontrol',
            options={'ordering': ['-date'], 'verbose_name': 'Control de Material', 'verbose_name_plural': 'Control de Materiales'},
        ),
        migrations.AddField(
            model_name='materialcontrol',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='materialcontrol',
            name='operation',
            field=models.CharField(choices=[('ADD', 'Entrada'), ('REMOVE', 'Salida'), ('TRANSFER', 'Traslado')], max_length=10, verbose_name='Operación'),
        ),
        migrations.AlterField(
            model_name='materialcontrol',
            name='reason',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('RETIRADA', 'Retirada'), ('USO', 'Uso en reporte'), ('DEVOLUCION', 'Devolución'), ('TRASLADO', 'Traslado'), ('CUADRE', 'Cuadre de inventario')], max_length=20, verbose_name='Motivo'),
        ),
    ]
