# Generated by Django 5.1.7 on 2025-03-10 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0005_add_ticket_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'ordering': ['warehouse__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('minimum_quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad mínima')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='materials.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Ubicación de material',
                'verbose_name_plural': 'Ubicaciones de materiales',
            },
        ),
        migrations.CreateModel(
            name='MaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('operation', models.CharField(choices=[('ADD', 'Entrada'), ('REMOVE', 'Salida'), ('TRANSFER', 'Traslado')], max_length=10, verbose_name='Operación')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='materials.material', verbose_name='Material')),
                ('material_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='materials.materialcontrol', verbose_name='Control de material')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_movements', to='storage.materiallocation', verbose_name='Ubicación origen')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_movements', to='storage.materiallocation', verbose_name='Ubicación destino')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de material',
                'verbose_name_plural': 'Movimientos de materiales',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='storage.department', verbose_name='Dependencia')),
            ],
            options={
                'verbose_name': 'Estantería',
                'verbose_name_plural': 'Estanterías',
                'ordering': ['department__warehouse__name', 'department__name', 'name'],
                'unique_together': {('department', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Tray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trays', to='storage.shelf', verbose_name='Estantería')),
            ],
            options={
                'verbose_name': 'Balda',
                'verbose_name_plural': 'Baldas',
                'ordering': ['shelf__department__warehouse__name', 'shelf__department__name', 'shelf__name', 'name'],
                'unique_together': {('shelf', 'code')},
            },
        ),
        migrations.AddField(
            model_name='materiallocation',
            name='tray',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='storage.tray', verbose_name='Balda'),
        ),
        migrations.AddField(
            model_name='department',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='storage.warehouse', verbose_name='Almacén'),
        ),
        migrations.AlterUniqueTogether(
            name='materiallocation',
            unique_together={('material', 'tray')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('warehouse', 'code')},
        ),
    ]
