# Generated by Django 5.1.7 on 2025-03-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tray',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
    ]
