# Generated by Django 5.1.7 on 2025-03-12 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_materialcontrol_location_reference'),
        ('storage', '0002_alter_department_code_alter_shelf_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiallocation',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Ubicación de Material', 'verbose_name_plural': 'Ubicaciones de Materiales'},
        ),
        migrations.AlterUniqueTogether(
            name='materiallocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='materiallocation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materiallocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='materiallocation',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='materials.material'),
        ),
        migrations.AlterField(
            model_name='materiallocation',
            name='minimum_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materiallocation',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materiallocation',
            name='tray',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_locations', to='storage.tray'),
        ),
        migrations.AlterField(
            model_name='materiallocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='materiallocation',
            constraint=models.UniqueConstraint(fields=('material', 'tray'), name='unique_material_tray'),
        ),
    ]
