# Generated by Django 3.2.25 on 2025-03-01 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='reported_by',
        ),
    ]
