# Generated by Django 3.2.25 on 2025-03-01 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0002_remove_incident_reported_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to='users.user', verbose_name='Reportado por'),
            preserve_default=False,
        ),
    ]
