# Generated by Django 5.1.7 on 2025-03-17 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_business_name_customer_tax_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del contrato')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('EXPIRED', 'Vencido')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('requires_maintenance', models.BooleanField(default=False, verbose_name='Requiere mantenimiento')),
                ('maintenance_frequency', models.CharField(blank=True, choices=[('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quincenal'), ('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('SEMIANNUAL', 'Semestral'), ('ANNUAL', 'Anual')], max_length=20, null=True, verbose_name='Frecuencia de mantenimiento')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Próxima fecha de mantenimiento')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('file', models.FileField(upload_to='contract_documents/', verbose_name='Archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract', verbose_name='Contrato')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contract_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento del contrato',
                'verbose_name_plural': 'Documentos del contrato',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción del trabajo')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas trabajadas')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('COMPLETED', 'Completado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='contracts.contract', verbose_name='Contrato')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_reports', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Reporte de contrato',
                'verbose_name_plural': 'Reportes de contrato',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de mantenimiento')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completado'), ('PARTIAL', 'Parcial'), ('PENDING', 'Pendiente')], default='COMPLETED', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='contracts.contract', verbose_name='Contrato')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Registro de mantenimiento',
                'verbose_name_plural': 'Registros de mantenimiento',
                'ordering': ['-date'],
            },
        ),
    ]
