# Generated by Django 5.1.7 on 2025-03-20 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_rename_notes_maintenancerecord_observations_and_more'),
        ('materials', '0011_alter_materialcontrol_options_materialcontrol_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractreport',
            options={'ordering': ['-date'], 'verbose_name': 'Reporte de contrato', 'verbose_name_plural': 'Reportes de contratos'},
        ),
        migrations.RemoveField(
            model_name='contractreport',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='contractreport',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='contractreport',
            name='title',
        ),
        migrations.AlterField(
            model_name='contractreport',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='contractreport',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contractreport',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractreport',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contractreport',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='contractreport',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contractreport',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('COMPLETED', 'Completado'), ('DELETED', 'Eliminado')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='ContractReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contract_report_images/%Y/%m/%d/', verbose_name='Imagen')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('image_type', models.CharField(choices=[('BEFORE', 'Antes'), ('AFTER', 'Después')], max_length=6, verbose_name='Tipo de imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contracts.contractreport', verbose_name='Reporte de contrato')),
            ],
            options={
                'verbose_name': 'Imagen de reporte de contrato',
                'verbose_name_plural': 'Imágenes de reportes de contrato',
            },
        ),
        migrations.CreateModel(
            name='ContractReportMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('contract_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_used', to='contracts.contractreport', verbose_name='Reporte de contrato')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Material usado en reporte de contrato',
                'verbose_name_plural': 'Materiales usados en reportes de contrato',
                'unique_together': {('contract_report', 'material')},
            },
        ),
        migrations.CreateModel(
            name='ContractReportTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='contracts.contractreport', verbose_name='Reporte de contrato')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Técnico asignado a reporte de contrato',
                'verbose_name_plural': 'Técnicos asignados a reportes de contrato',
                'unique_together': {('contract_report', 'technician')},
            },
        ),
    ]
