# Generated by Django 5.1.7 on 2025-03-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_deleted_at_ticket_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketitem',
            name='location_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación de origen'),
        ),
    ]
