# Generated by Django 5.1.7 on 2025-03-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketitem_location_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketitem',
            name='location_source',
            field=models.CharField(blank=True, help_text='Ruta completa de la ubicación de origen', max_length=255, null=True, verbose_name='Ubicación de origen'),
        ),
    ]
